title: Ashutosh Kumar
logo: /assets/img/profile.png
description: Third year PhD student at the Machine and Language Learning Lab, Indian Institute of Science
show_downloads: false
google_analytics: UA-58099446-1
theme: jekyll-theme-minimal
