title: Ashutosh Kumar
logo: /assets/img/profile.png
githubimg: /assets/img/github.svg
twitterimg: /assets/img/twitter.svg
linkedinimg: /assets/img/linkedin.svg
mediumimg: /assets/img/medium.svg
scholarimg: /assets/img/googlescholar.svg
goodreadsimg: /assets/img/goodreads.svg
scholar: https://scholar.google.co.in/citations?user=XpfyeOgAAAAJ
twitter: https://twitter.com/ashutoshk2401
medium: https://ashutoshk2401.medium.com
linkedin: https://www.linkedin.com/in/ashutosh-kumar-04a0325b/
goodreads: https://www.goodreads.com/user/show/51184901-ashutosh
description:
show_downloads: false
google_analytics: UA-58099446-1
theme: jekyll-theme-minimal
author: Ashutosh
sass:
  load_paths:
    - node_modules
exclude: []
