title: Ashutosh Kumar
logo: /assets/img/profile.png
githubimg: /assets/img/github.svg
twitterimg: /assets/img/twitter.svg
linkedinimg: /assets/img/linkedin.svg
quoraimg: /assets/img/quora.svg
scholar: https://scholar.google.co.in/citations?user=XpfyeOgAAAAJ
twitter: https://twitter.com/ashutoshk2401
quora: https://www.quora.com/profile/Ashutosh-Kumar-16
linkedin: https://www.linkedin.com/in/ashutosh-kumar-04a0325b/
description:
show_downloads: false
google_analytics: UA-58099446-1
theme: jekyll-theme-minimal
author: Ashutosh
sass:
  load_paths:
    - node_modules
exclude: []
